export const DOGFOOD_ROUTE_CASES = [
  { query: 'fix failing tests and create a PR', combo: 'test_pr_repair', category: 'pr' },
  { query: '帮我修失败测试并提交 PR', combo: 'test_pr_repair', category: 'pr' },
  { query: '修测试然后开 PR', combo: 'test_pr_repair', category: 'pr' },
  { query: 'failed tests pull request handoff', combo: 'test_pr_repair', category: 'pr' },
  { query: 'test failure create a pull request', combo: 'test_pr_repair', category: 'pr' },
  { query: 'create a PR', combo: 'test_pr_repair', category: 'pr' },
  { query: 'open a pull request', combo: 'test_pr_repair', category: 'pr' },
  { query: '帮我开 PR', combo: 'test_pr_repair', category: 'pr' },
  { query: 'review this PR for regressions', combo: 'code_review_regression', category: 'review' },
  { query: '审查这个 PR 的回归风险', combo: 'code_review_regression', category: 'review' },
  { query: 'code review risk and missing tests', combo: 'code_review_regression', category: 'review' },
  { query: 'production release privacy hook rollback', combo: 'release_public_audit', category: 'release' },
  { query: '检查公开安装 hook 的隐私和回滚风险，然后准备 release', combo: 'release_public_audit', category: 'release' },
  { query: 'publish npm release with privacy audit', combo: 'release_public_audit', category: 'release' },
  { query: '查 hook ， release', combo: 'release_public_audit', category: 'release' },
  { query: '帮我重新规划产品方向和执行方案', combo: 'product_direction_planning', category: 'product' },
  { query: 'replan product direction and execution plan', combo: 'product_direction_planning', category: 'product' },
  { query: 'office hours product strategy', combo: 'product_direction_planning', category: 'product' },
  { query: '请用 council 议会模式裁决架构取舍', combo: 'council_escalation', category: 'council', choice: 'mode:council' },
  { query: 'irreversible cost decision council mode', combo: 'council_escalation', category: 'council', choice: 'mode:council' },
  { query: '架构决策不可逆，议会裁决', combo: 'council_escalation', category: 'council', choice: 'mode:council' },
  { query: '这个 bug 崩溃了，帮我排查报错', combo: 'debug_crash', category: 'debug' },
  { query: 'bug ，帮查', combo: 'debug_crash', category: 'debug' },
  { query: 'debug this crash error', combo: 'debug_crash', category: 'debug' },
  { query: 'broken workflow failing command', combo: 'debug_crash', category: 'debug' },
  { query: 'local server stuck with no output', combo: 'debug_stuck_runtime', category: 'debug' },
  { query: '进程卡住长时间无输出', combo: 'debug_stuck_runtime', category: 'debug' },
  { query: 'clean up AI generated slop code', combo: 'refactor_clean', category: 'refactor' },
  { query: '清理这段臃肿的垃圾代码', combo: 'refactor_clean', category: 'refactor' },
  { query: 'refactor this function to simplify duplicated code', combo: 'refactor_clean', category: 'refactor' },
  { query: '检查认证权限和密钥泄漏安全风险', combo: 'audit_security', category: 'security' },
  { query: 'audit auth permission secret vulnerability', combo: 'audit_security', category: 'security' },
  { query: 'build a new frontend settings screen', combo: 'frontend_new_page', category: 'frontend' },
  { query: '新增一个前端设置页面', combo: 'frontend_new_page', category: 'frontend' },
  { query: 'redesign existing page', combo: 'frontend_existing_redesign', category: 'frontend' },
  { query: '优化现有网页界面', combo: 'frontend_existing_redesign', category: 'frontend' },
  { query: 'build CEO dashboard metrics', combo: 'dashboard_ceo', category: 'dashboard' },
  { query: '把后台改成 CEO dashboard 运营指标看板', combo: 'dashboard_ceo', category: 'dashboard' },
  { query: 'write public install docs README', combo: 'docs_public_install', category: 'docs' },
  { query: '把安装流程写给普通用户，更新 README', combo: 'docs_public_install', category: 'docs' },
] as const;

export type DogfoodRouteCase = typeof DOGFOOD_ROUTE_CASES[number];
