/**
 * LazyBrain — Core Type Definitions
 *
 * This file defines the global contracts for the entire system.
 * All modules depend on these types. Do not modify without reviewing
 * all downstream consumers.
 */

// ─── Capability (Graph Node) ────────────────────────────────────────────────

export type CapabilityKind = 'skill' | 'agent' | 'command' | 'mode' | 'hook';

export type Platform =
  | 'claude-code'
  | 'openclaw'
  | 'workbuddy'
  | 'cursor'
  | 'kiro'
  | 'codex'
  | 'opencode'
  | 'hermes'
  | 'droid'
  | 'universal';

export interface CapabilityMeta {
  stars?: number;
  reviews?: number;
  url?: string;
  version?: string;
  lastUpdated?: string;
}

/**
 * A single capability node in the knowledge graph.
 * Represents a skill, agent, command, mode, or hook.
 */
export interface Capability {
  /** Deterministic ID: sha256(kind + ":" + name + ":" + origin) */
  id: string;
  kind: CapabilityKind;
  name: string;
  description: string;
  /** Source ecosystem: "ECC", "OMC", "plugin", "external", etc. */
  origin: string;
  /** Installation status */
  status: 'installed' | 'available' | 'disabled';
  /** Platforms this capability works on */
  compatibility: Platform[];
  /** Local file path (only for installed capabilities) */
  filePath?: string;

  // ─── LLM-compiled enrichments ───
  /** Semantic tags generated by LLM compiler */
  tags: string[];
  /** Example user queries that should match this capability */
  exampleQueries: string[];
  /** Functional domain category */
  category: string;
  /** One-line scenario description: when to use this */
  scenario?: string;
  /**
   * Template for human-readable match explanation.
   * Variables: {query_tags}, {history_hint}, {tool_name}
   * Example: '你提到 {query_tags}，这些词在 {tool_name} 的典型用例里。{history_hint}'
   */
  explanation_template?: string;

  // ─── Frontmatter-extracted ───
  /** Original trigger keywords from SKILL.md frontmatter */
  triggers?: string[];

  /** Author-defined trigger aliases (e.g. "ap" for autopilot, "ulw" for ultrawork) */
  aliases?: string[];

  /** Compilation tier: 0=current platform, 1=universal, 2=other platforms */
  tier?: 0 | 1 | 2;

  /** External metadata (stars, reviews, url) */
  meta?: CapabilityMeta;

  // ─── User-evolved tags ───
  /** Tags learned from user behavior (降权 0.6x，上限 5 个） */
  evolvedTags?: string[];

  // ─── Phase 3.x: Execution Governance ───
  /** Cost level for budget gating */
  costLevel?: 'free' | 'low' | 'medium' | 'high';
  /** Risk level for preflight gating */
  riskLevel?: 'safe' | 'caution' | 'destructive';
  /** Require user confirmation before execution */
  requiresConfirmation?: boolean;
  /** Hide from default recommendations (shown only on explicit query) */
  hiddenByDefault?: boolean;
  /** Source priority for duplicate resolution (0=highest) */
  sourcePriority?: number;
  /** Other capability names this overlaps with (for duplicate warnings) */
  overlapsWith?: string[];
}

/**
 * Governance decision for a matched capability.
 * Produced by the governance layer before presenting to the user.
 */
export interface GovernanceDecision {
  /** Recommended execution mode */
  mode: ExecutionMode;
  /** Whether to show a confirmation prompt */
  requiresConfirmation: boolean;
  /** Level of confirmation needed */
  confirmationLevel: 'none' | 'soft' | 'hard';
  /** Estimated input tokens for this execution */
  estimatedInputTokens: number;
  /** Estimated output tokens for this execution */
  estimatedOutputTokens: number;
  /** Estimated cost in USD (approximate) */
  estimatedCostUsd: number;
  /** Estimated duration in minutes */
  estimatedDurationMinutes: number;
  /** Which model plan was selected */
  selectedModelPlan: 'haiku' | 'sonnet' | 'opus' | 'custom';
  /** Reasons for the selected model plan */
  reasons: string[];
  /** Option to downgrade to a cheaper model */
  downgradeOption?: {
    plan: string;
    estimatedCostUsd: number;
    tradeoffs: string;
  };
}

// ─── Link (Graph Edge) ──────────────────────────────────────────────────────

export type LinkType =
  | 'similar_to'      // Functionally similar, needs comparison
  | 'composes_with'   // Can be used together
  | 'supersedes'      // Replaces an older version
  | 'depends_on'      // Requires another capability
  | 'belongs_to';     // Ecosystem membership

/**
 * A bidirectional edge between two capabilities.
 */
export interface Link {
  source: string;  // Capability ID
  target: string;  // Capability ID
  type: LinkType;
  /** Human-readable explanation of the relationship */
  description?: string;
  /** For similar_to: what's the difference */
  diff?: string;
  /** Confidence score from LLM inference (0-1) */
  confidence: number;
}

// ─── Graph ──────────────────────────────────────────────────────────────────

/**
 * The full capability knowledge graph, serialized to graph.json.
 */
export interface CapabilityGraph {
  version: string;
  compiledAt: string;
  compileModel?: string;
  nodes: Capability[];
  links: Link[];
  categories: string[];
}

// ─── Match Result ───────────────────────────────────────────────────────────

export type MatchLayer = 'alias' | 'tag' | 'semantic' | 'llm';
export type Confidence = 'high' | 'medium' | 'low';

export interface MatchResult {
  capability: Capability;
  /** Combined score 0-1 */
  score: number;
  /** Which layer produced this match */
  layer: MatchLayer;
  confidence: Confidence;
  /** History boost applied (0-1), only set when boost > 0 */
  historyBoost?: number;
  /** Human-readable explanation (filled from explanation_template at match time) */
  explanation?: string;
}

/**
 * Enriched recommendation after graph traversal.
 */
export interface Recommendation {
  /** Primary matches */
  matches: MatchResult[];
  /** Similar capabilities with diff explanations */
  comparisons: Array<{
    a: Capability;
    b: Capability;
    diff: string;
  }>;
  /** Suggested combinations */
  compositions: Array<{
    capabilities: Capability[];
    reason: string;
  }>;
  /** Version upgrade suggestions */
  upgrades: Array<{
    old: Capability;
    new: Capability;
  }>;
  /** Available but not installed */
  external: MatchResult[];
  /** Warnings or info messages */
  warnings?: string[];
  /** Predicted next steps (from current session task chains) */
  nextSteps?: string[];
  /** Decision type hint (analysis, complex_impl, ambiguous, research, team_task) */
  decisionHint?: {
    type: string;
    reason: string;
    suggestedTools: string[];
    note: string;
  };
}

// ─── Wiki Card ────────────────────────────────────────────────────────────────

export interface WikiCard {
  capability: Capability;
  primaryUse?: string;
  composesWith: Array<{
    capability: Capability;
    reason: string;
  }>;
  similarTo: Array<{
    capability: Capability;
    diff: string;
  }>;
  dependsOn: Array<{
    capability: Capability;
  }>;
  tags: string[];
  topExampleQueries: string[];
}

// ─── Secretary ────────────────────────────────────────────────────────────────

export interface SecretaryConfig {
  /** Enable secretary layer */
  enabled: boolean;
  /** Timeout for secretary LLM call in ms */
  timeoutMs: number;
  /** Rate limit: same session cooldown in ms */
  rateLimitMs: number;
  /** Confidence threshold to skip secretary */
  confidenceThreshold: number;
  /** Confidence threshold to call secretary */
  lowConfidenceThreshold: number;
  /** Circuit breaker: pause after N consecutive failures */
  circuitBreakerThreshold: number;
  /** Circuit breaker: pause duration in ms */
  circuitBreakerPauseMs: number;
}

export interface SecretaryTask {
  /** skill/agent/command name */
  action: string;
  /** 建议模型: sonnet | opus | haiku */
  model?: string;
  /** 为什么推荐这个 */
  reason: string;
  /** 依赖哪个前置任务（编排顺序） */
  after?: string;
}

export type ExecutionMode = 'regular' | 'ralplan' | 'team' | 'ralph';

export interface SecretaryResponse {
  /** 是否需要工具（模糊讨论/闲聊 = false） */
  needsTool: boolean;
  /** 一句话意图摘要 */
  intent: string;
  /** 执行模式建议 */
  mode?: ExecutionMode;
  /** 为什么选这个模式 */
  modeReason?: string;
  /** 编排后的任务列表 */
  tasks: SecretaryTask[];
  /** 推荐置信度 0-1 */
  confidence: number;
  /** 执行方案摘要 */
  plan: string;
  /** 推理过程 */
  reasoning: string;
  /** 预测的下一步可选工具（从历史 task chains 推断） */
  nextSteps?: string[];
}

export interface ProposalOption {
  id: 'A' | 'B' | 'C';
  label: string;
  model: string;
  estimatedTokens: number;
  savings: number;       // 0-1, fraction vs Opus baseline
  reason: string;
}

// ─── User Config ────────────────────────────────────────────────────────────

export type MatchMode = 'auto' | 'select' | 'ask';
export type MatchEngine = 'tag' | 'llm';
export type RoutingStrategy = 'always-main' | 'optimal' | 'ask';

export interface UserConfig {
  /** User-defined aliases: "疯狗模式" → "ralph" */
  aliases: Record<string, string>;
  /** Custom scan paths (in addition to defaults) */
  scanPaths: string[];
  /** Auto-trigger or show selection list */
  mode: MatchMode;
  /** Auto-trigger threshold (0-1) */
  autoThreshold: number;
  /** Which matching engine(s) to use */
  engine: MatchEngine;
  /** Routing strategy: always-main (no proposals), optimal (auto-pick cheapest), ask (show all) */
  strategy: RoutingStrategy;
  /** LLM model for compilation */
  compileModel: string;
  /** LLM API base URL (for MiniMax mirror, Ollama, etc.) */
  compileApiBase?: string;
  /** LLM API key */
  compileApiKey?: string;
  /** Secretary API base URL (独立配置，SiliconFlow 免费) */
  secretaryApiBase?: string;
  /** Secretary API key */
  secretaryApiKey?: string;
  /** Secretary model name */
  secretaryModel?: string;
  /** Enable external capability discovery */
  externalDiscovery: boolean;
  /** Current platform (auto-detected or manual) */
  platform: Platform;
  /** UI language */
  language: 'auto' | 'en' | 'zh';
  /** Platforms to compile (default: auto-detect current) */
  compilePlatforms?: Platform[];
  /** Platforms to scan (default: only current platform) */
  platforms?: Record<Platform, boolean>;
  /** Decision card threshold (0-1): score >= threshold shows decision card, below uses compact output */
  decisionCardThreshold?: number;

  // ─── Phase 3.x: Governance ───
  /** Execution governance configuration */
  governance?: {
    /** Enable preflight checks before execution */
    enablePreflight: boolean;
    /** Soft cost limit in USD (warn above this) */
    softCostUsd: number;
    /** Hard cost limit in USD (block above this) */
    hardCostUsd: number;
    /** Soft token threshold (warn above this) */
    softTokenThreshold: number;
    /** Hard token threshold (block above this) */
    hardTokenThreshold: number;
    /** Modes that are considered "heavy" and require extra gating */
    heavyModes: ExecutionMode[];
  };
  /** Hook runtime safety controls */
  hookSafety?: {
    maxConcurrentHooks?: number;
    staleHookMs?: number;
    avgDurationBreakerMs?: number;
    loadAvgBreaker?: number;
    breakerCooldownMs?: number;
    recentDurationsWindow?: number;
  };
}

// ─── History ────────────────────────────────────────────────────────────────

export interface HistoryEntry {
  timestamp: string;
  query: string;
  matched: string;
  id?: string;
  accepted: boolean;
  layer: MatchLayer;
  sessionId?: string;
  candidateList?: string[];
  chosenInstead?: string;
  /** Why this entry was recorded: 'matched' | 'no_match' | 'low_score' | 'secretary_rejected' | 'error' */
  reason?: string;
}

// ─── User Profile (distilled from history) ─────────────────────────────────

export interface ToolAffinity {
  name: string;
  id?: string;
  totalUses: number;
  acceptRate: number;
  /** 最近一次使用 */
  lastUsed: string;
  /** 拒绝次数 */
  rejectCount: number;
}

export interface TaskChain {
  /** 工具序列 e.g. ["code-review", "simplify", "commit"] */
  sequence: string[];
  /** 出现次数 */
  count: number;
}

export interface CorrectionSignal {
  /** 被拒绝的工具 */
  rejected: string;
  /** 用户选择的替代工具 */
  chosen: string;
  /** 同 session 内被拒绝 + 选 B 的次数 */
  count: number;
}

export interface UserProfile {
  /** 蒸馏时间 */
  distilledAt: string;
  /** 事件总数（蒸馏时的 history 行数） */
  eventCount: number;
  /** 工具亲和度（按使用频次降序） */
  toolAffinities: ToolAffinity[];
  /** 常见任务链（连续 session 内的工具序列） */
  taskChains: TaskChain[];
  /** 偏好模型（从 history 中推断） */
  preferredLayer: MatchLayer;
  /** 能力信号：高级工具占比 */
  advancedToolRatio: number;
  /** 纠正信号：被拒工具 → 替代工具 */
  corrections?: CorrectionSignal[];

  // ─── Phase 3.2: Usage-based profile ──────────────────────────────────────
  /** usage.jsonl 中的 session 总数 */
  sessionCount: number;
  /** taskType 分布 { taskType: count } */
  taskTypeDistribution: Record<string, number>;
  /** 热门 taskType Top3 */
  topTaskTypes: Array<{ type: string; count: number }>;
  /** 平均每次 session 的 input tokens */
  avgInputTokens: number;
  /** 平均每次 session 的 output tokens */
  avgOutputTokens: number;
  /** 平均每次 session 的总 cost (USD) */
  avgSessionCost: number;
  /** 总累计 cost (USD) */
  totalCost: number;
  /** 平均每次 session 使用的 agent 数量 */
  avgAgentsPerSession: number;
  /** 是否建议使用 agent 组合（agent 数量 >= 2 的 session 占比 >= 30%） */
  shouldUseAgentComposition: boolean;
  /** 使用的 agent 类型列表 */
  agentTypesUsed: string[];
}

// ─── Scanner ────────────────────────────────────────────────────────────────

/**
 * Raw parsed capability before LLM compilation.
 * Scanner output → Compiler input.
 */
export interface RawCapability {
  kind: CapabilityKind;
  name: string;
  description: string;
  origin: string;
  filePath: string;
  triggers?: string[];
  compatibility: Platform[];
  meta?: CapabilityMeta;
  /** Compilation tier assigned by scanner */
  tier?: 0 | 1 | 2;
  /** True if scanned from skills-disabled path */
  disabled?: boolean;
  /** Primary platform this capability was scanned from */
  platform?: Platform;
}

// ─── LLM Provider ───────────────────────────────────────────────────────────

export interface LLMProviderConfig {
  model: string;
  apiBase: string;
  apiKey?: string;
  runtimePlatform?: Platform;
}

export interface LLMResponse {
  content: string;
  inputTokens: number;
  outputTokens: number;
}

export interface LLMProvider {
  complete(prompt: string, systemPrompt?: string): Promise<LLMResponse>;
}
